name: weatherer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animated_icons: ^1.0.1
  flutter_launcher_icons: ^0.14.3
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  google_fonts: ^6.2.1
  http: ^1.3.0
  lottie: ^1.3.0
  riverpod: ^2.6.1
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
